// GENERATED by scripts/garden2/export.py from brand/garden2/app-export (mockup v8). Do not edit by hand.

import type { Plant2 } from './layout'

export const PLATE = require('../../assets/garden2/plate.png')
export const OVERLAY_SRC = {
  stand: require('../../assets/garden2/stand.png'),
  cords: require('../../assets/garden2/cords.png'),
} as const

/** Every stage layer, indexed by plant then stage. */
export const STAGE_SRC: Record<Plant2, Record<number, number>> = {
  maple: {
    0: require('../../assets/garden2/maple/stage00.webp'),
    1: require('../../assets/garden2/maple/stage01.webp'),
    2: require('../../assets/garden2/maple/stage02.webp'),
    3: require('../../assets/garden2/maple/stage03.webp'),
    4: require('../../assets/garden2/maple/stage04.webp'),
    5: require('../../assets/garden2/maple/stage05.webp'),
    6: require('../../assets/garden2/maple/stage06.webp'),
    7: require('../../assets/garden2/maple/stage07.webp'),
    8: require('../../assets/garden2/maple/stage08.webp'),
    9: require('../../assets/garden2/maple/stage09.webp'),
    10: require('../../assets/garden2/maple/stage10.webp'),
    11: require('../../assets/garden2/maple/stage11.webp'),
    12: require('../../assets/garden2/maple/stage12.webp'),
    13: require('../../assets/garden2/maple/stage13.webp'),
    14: require('../../assets/garden2/maple/stage14.webp'),
  },
  store: {
    0: require('../../assets/garden2/store/stage00.webp'),
    1: require('../../assets/garden2/store/stage01.webp'),
    2: require('../../assets/garden2/store/stage02.webp'),
    3: require('../../assets/garden2/store/stage03.webp'),
    4: require('../../assets/garden2/store/stage04.webp'),
    5: require('../../assets/garden2/store/stage05.webp'),
    6: require('../../assets/garden2/store/stage06.webp'),
    7: require('../../assets/garden2/store/stage07.webp'),
    8: require('../../assets/garden2/store/stage08.webp'),
    9: require('../../assets/garden2/store/stage09.webp'),
    10: require('../../assets/garden2/store/stage10.webp'),
    11: require('../../assets/garden2/store/stage11.webp'),
    12: require('../../assets/garden2/store/stage12.webp'),
    13: require('../../assets/garden2/store/stage13.webp'),
    14: require('../../assets/garden2/store/stage14.webp'),
  },
  mandarin: {
    0: require('../../assets/garden2/mandarin/stage00.webp'),
    1: require('../../assets/garden2/mandarin/stage01.webp'),
    2: require('../../assets/garden2/mandarin/stage02.webp'),
    3: require('../../assets/garden2/mandarin/stage03.webp'),
    4: require('../../assets/garden2/mandarin/stage04.webp'),
    5: require('../../assets/garden2/mandarin/stage05.webp'),
    6: require('../../assets/garden2/mandarin/stage06.webp'),
    7: require('../../assets/garden2/mandarin/stage07.webp'),
    8: require('../../assets/garden2/mandarin/stage08.webp'),
    9: require('../../assets/garden2/mandarin/stage09.webp'),
    10: require('../../assets/garden2/mandarin/stage10.webp'),
    11: require('../../assets/garden2/mandarin/stage11.webp'),
    12: require('../../assets/garden2/mandarin/stage12.webp'),
    13: require('../../assets/garden2/mandarin/stage13.webp'),
    14: require('../../assets/garden2/mandarin/stage14.webp'),
  },
  pothos: {
    0: require('../../assets/garden2/pothos/stage00.webp'),
    1: require('../../assets/garden2/pothos/stage01.webp'),
    2: require('../../assets/garden2/pothos/stage02.webp'),
    3: require('../../assets/garden2/pothos/stage03.webp'),
    4: require('../../assets/garden2/pothos/stage04.webp'),
    5: require('../../assets/garden2/pothos/stage05.webp'),
    6: require('../../assets/garden2/pothos/stage06.webp'),
    7: require('../../assets/garden2/pothos/stage07.webp'),
    8: require('../../assets/garden2/pothos/stage08.webp'),
    9: require('../../assets/garden2/pothos/stage09.webp'),
    10: require('../../assets/garden2/pothos/stage10.webp'),
    11: require('../../assets/garden2/pothos/stage11.webp'),
    12: require('../../assets/garden2/pothos/stage12.webp'),
    13: require('../../assets/garden2/pothos/stage13.webp'),
    14: require('../../assets/garden2/pothos/stage14.webp'),
  },
  orchid: {
    0: require('../../assets/garden2/orchid/stage00.webp'),
    1: require('../../assets/garden2/orchid/stage01.webp'),
    2: require('../../assets/garden2/orchid/stage02.webp'),
    3: require('../../assets/garden2/orchid/stage03.webp'),
    4: require('../../assets/garden2/orchid/stage04.webp'),
    5: require('../../assets/garden2/orchid/stage05.webp'),
    6: require('../../assets/garden2/orchid/stage06.webp'),
    7: require('../../assets/garden2/orchid/stage07.webp'),
    8: require('../../assets/garden2/orchid/stage08.webp'),
    9: require('../../assets/garden2/orchid/stage09.webp'),
    10: require('../../assets/garden2/orchid/stage10.webp'),
    11: require('../../assets/garden2/orchid/stage11.webp'),
    12: require('../../assets/garden2/orchid/stage12.webp'),
    13: require('../../assets/garden2/orchid/stage13.webp'),
    14: require('../../assets/garden2/orchid/stage14.webp'),
  },
  azalea: {
    0: require('../../assets/garden2/azalea/stage00.webp'),
    1: require('../../assets/garden2/azalea/stage01.webp'),
    2: require('../../assets/garden2/azalea/stage02.webp'),
    3: require('../../assets/garden2/azalea/stage03.webp'),
    4: require('../../assets/garden2/azalea/stage04.webp'),
    5: require('../../assets/garden2/azalea/stage05.webp'),
    6: require('../../assets/garden2/azalea/stage06.webp'),
    7: require('../../assets/garden2/azalea/stage07.webp'),
    8: require('../../assets/garden2/azalea/stage08.webp'),
    9: require('../../assets/garden2/azalea/stage09.webp'),
    10: require('../../assets/garden2/azalea/stage10.webp'),
    11: require('../../assets/garden2/azalea/stage11.webp'),
    12: require('../../assets/garden2/azalea/stage12.webp'),
    13: require('../../assets/garden2/azalea/stage13.webp'),
    14: require('../../assets/garden2/azalea/stage14.webp'),
  },
}

/** R533: the trees' earnings sprites, one per tree (the ripe mandarin, the open ORE-gold flower). */
export const FRUIT_SRC = {
  mandarin: require('../../assets/garden2/mandarin-fruit.png'),
  store: require('../../assets/garden2/store-fruit.png'),
} as const

/** R534/R535: the app-drawn decor sprites. */
export const DECOR_SRC = {
  basket: require('../../assets/garden2/decor-basket.png'),
} as const

/** R529 dark mode: the dark plate (null until one is exported) and any dark variants of overlays and stage layers. */
export const PLATE_DARK: number | null = null
export const OVERLAY_SRC_DARK: Partial<Record<'stand' | 'cords', number>> = {
}
export const STAGE_SRC_DARK: Partial<Record<Plant2, Record<number, number>>> = {
}
