// GENERATED by brand/garden/bake.py. Do not edit. The opening strips (RG24 part two): one density mask per leaf shape, 16 frames at 3x; 1x units.
export type StripMeta = { src: number; frames: number; w: number; h: number; ay: number; L: number };
export const STRIPS: Record<string, StripMeta> = {
  blade: { src: require("@/assets/garden/strips/blade.png"), frames: 16, w: 32, h: 32, ay: 29.76, L: 26.88 },
  heart: { src: require("@/assets/garden/strips/heart.png"), frames: 16, w: 32, h: 32, ay: 29.76, L: 26.88 },
  broad: { src: require("@/assets/garden/strips/broad.png"), frames: 16, w: 32, h: 32, ay: 29.76, L: 26.88 },
  small: { src: require("@/assets/garden/strips/small.png"), frames: 16, w: 32, h: 32, ay: 29.76, L: 26.88 },
};
