// GENERATED by brand/garden/bake.py. Do not edit. The opening strips (RG24 part two): one coloured wash per species and leaf shape, 16 frames at 3x; 1x units.
export type StripMeta = { src: number; frames: number; w: number; h: number; ay: number; L: number };
export const STRIPS: Record<string, StripMeta> = {
  "skr-blade": { src: require("@/assets/garden/strips/skr-blade.png"), frames: 16, w: 32, h: 32, ay: 29.76, L: 26.88 },
  "ore-blade": { src: require("@/assets/garden/strips/ore-blade.png"), frames: 16, w: 32, h: 32, ay: 29.76, L: 26.88 },
  "hsol-broad": { src: require("@/assets/garden/strips/hsol-broad.png"), frames: 16, w: 32, h: 32, ay: 29.76, L: 26.88 },
  "jitosol-blade": { src: require("@/assets/garden/strips/jitosol-blade.png"), frames: 16, w: 32, h: 32, ay: 29.76, L: 26.88 },
  "jupsol-small": { src: require("@/assets/garden/strips/jupsol-small.png"), frames: 16, w: 32, h: 32, ay: 29.76, L: 26.88 },
};
