// GENERATED by brand/garden/wind12.py (R200, the painted wind curls). Do not edit. Boxes in 1x units; each curl runs left to
// right (the direction of the wind), the brush landing at the left edge and the curl at the right.
export type WindSprite = { src: number; w: number; h: number };
export const WIND_SPRITES: Record<string, WindSprite> = {
  "wind-a": { src: require("@/assets/garden/wind-a.png"), w: 77, h: 24 },
  "wind-b": { src: require("@/assets/garden/wind-b.png"), w: 54, h: 23 },
  "wind-c": { src: require("@/assets/garden/wind-c.png"), w: 66, h: 20 },
};
export const WIND_NAMES = ["wind-a", "wind-b", "wind-c"] as const;
